name: fit_street
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / utilities
  google_fonts: ^4.0.4
  liquid_swipe: ^3.1.0
  gradient_borders: ^1.0.0
  glass: ^2.0.0+2
  glassmorphism: ^3.0.0
  liquid_glass_renderer: 0.1.1-dev.11
  # remove
  syncfusion_flutter_charts: ^26.1.0

  # Media / files
  image_picker: ^0.8.7+X
  file_picker: ^8.0.0
  mime: ^1.0.2
  path: ^1.8.0
  dio: ^5.2.1
  flutter_secure_storage: ^8.0.0
  flutter_image_compress: ^2.1.0
  path_provider: ^2.0.15

  # Signature / storage / i18n
  signature: ^5.5.0
  shared_preferences: ^2.0.0
  intl: ^0.18.0

  # Networking & state
  http: ^0.13.0
  provider: ^6.0.0

  # Misc
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  magnifying_glass: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/transparent_bull_logo.png"
  adaptive_icon_background: "#B0B0B0"  # light grey color
  adaptive_icon_foreground: "assets/image/transparent_bull_logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/image/

