// lib/constants/specializations.dart
// Single source of truth for specialization groups used across the app.

const Map<String, List<String>> kGroupedSpecializations = {
  'Fitness Training': [
    'Strength Training',
    'HIIT',
    'CrossFit',
    'Functional Training',
    'Cardio',
    'Aerobics',
    'Zumba',
    'Strength and Conditioning',
    'Endurance Training',
    'Circuit Training',
    'Dance Fitness',
  ],
  'Body Transformation': [
    'Weight Loss',
    'Weight Gain',
    'Bodybuilding',
    'Muscle Gain Expert',
    'Body Transformation',
    'Female Fitness',
    'Physique Enhancement Specialist',
  ],
  'Health & Rehabilitation': [
    'Rehabilitation Trainer',
    'Pain Management',
    'Injury Prevention',
    'Posture Correction',
    'Lifestyle Disorders',
    'Stretching Specialist',
    'Mobility & Flexibility Coach',
    'Physical Therapist Support',
  ],
  'Yoga & Meditation': [
    'Yoga',
    'Hatha Yoga',
    'Vinyasa Yoga',
    'Prenatal Yoga',
    'Postnatal Yoga',
    'Recreational Yoga',
    'Meditation',
    'Breathwork & Pranayama',
    'Sound Healing',
    'Mindfulness Trainer',
  ],
  'Specialized Fitness': [
    'Pilates Instructor',
    'Calisthenics Coach',
    'Core Strength Trainer',
    'Balance & Stability Training',
    'Sports Performance Coach',
  ],
  'Nutrition & Diet Planning': [
    'Nutrition',
    'Sports Nutritionist',
    'Weight Management Expert',
    'Diet Planning Specialist',
    'Holistic Nutrition Coach',
  ],
  'Mental Health & Counseling': [
    'Counselors',
    'Mental Counselor',
    'Psychologist',
    'Depression Support',
    'Stress Management',
    'Art Therapy',
    'Suicide Prevention',
    'Psychological First Aid',
    'Solution-Focused Brief Therapy',
    'Career Counseling',
    'Neuro-Linguistic Programming',
    'Relationship Therapist',
    'Martial Discord',
    'Reproductive Health Counselor',
  ],
  'Sports & Athletics': [
    'Cricket Coach',
    'Boxing Coach',
    'Martial Arts Instructor',
    'Football Trainer',
    'Tennis Coach',
    'Badminton Coach',
    'Athletic Performance Trainer',
  ],
};
